### ISSUE TITLE
Error when training with GPU: Dataset initialization failed: 'Dataflow' object has no attribute '_to_pyrecords'

### ISSUE THREAD

**Issue by lehmus** [microsoft/bert-stack-overflow#57]
I am trying to fine-tune the BERT model on a GPU. I have followed the instructions in the notebook 1-Training/AzureServiceClassifier_Training.ipynb. I am able to train the model using CPU but the GPU step fails. Here is a screenshot of the error:

![Train GPU error](https://user-images.githubusercontent.com/16114036/73678345-e2259380-46c0-11ea-9e03-7fd3951d6f34.png)

The same error happens with estimator2 (train_logging.py). Here is the full stack trace of the error:

```
Set Dataset azureservicedata's target path to /tmp/tmp6odb7z1e
Enter __enter__ of DatasetContextManager
Processing 'azureservicedata'
Processing dataset FileDataset
{
  "source": [
    "('tfworld', 'azure-service-classifier/data')"
  ],
  "definition": [
    "GetDatastoreFiles"
  ],
  "registration": {
    "id": "9e790eda-004e-4777-9865-02446ae26898",
    "name": "Azure Services Dataset",
    "version": 1,
    "description": "Dataset containing azure related posts on Stackoverflow",
    "workspace": "Workspace.create(name='<HIDDEN>', subscription_id='<HIDDEN>', resource_group='<HIDDEN>')"
  }
}
Mounting azureservicedata to /tmp/tmp6odb7z1e
2020-02-03 18:08:47.467988 | ActivityCompleted: Activity=mount, HowEnded=Failure, Duration=143.49 [ms], Info = {'activity_id': '42c866df-3d0b-4e7c-8c37-da794d34314a', 'activity_name': 'mount', 'activity_type': 'PublicApi', 'app_name': 'FileDataset', 'source': 'azureml.dataset', 'version': '1.0.85', 'completionStatus': 'Success', 'durationMs': 5040.52}, Exception=AttributeError; 'Dataflow' object has no attribute '_to_pyrecords'
Logging warning in history service: ERROR:: Dataset  failed. . Exception Details:Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/<HIDDEN>/azureml/bert-classifier-test_1580753255_d05099c4/mounts/workspaceblobstore/azureml/bert-classifier-test_1580753255_d05099c4/azureml-setup/context_managers.py", line 226, in __enter__
    self.datasets.__enter__()
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/context_managers.py", line 118, in __enter__
    context_manager = dataset.mount(mount_point=target_path)
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/_loggerfactory.py", line 78, in wrapper
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/file_dataset.py", line 191, in mount
    base_path = _find_path_prefix(self._dataflow)
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/file_dataset.py", line 281, in _find_path_prefix
    return None if path is None else _get_prefix(path, dataflow)
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/file_dataset.py", line 294, in _get_prefix
    paths = [r['PortablePath'] for r in dataflow.take(1)._to_pyrecords()]
AttributeError: 'Dataflow' object has no attribute '_to_pyrecords'

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/<HIDDEN>/azureml/bert-classifier-test_1580753255_d05099c4/mounts/workspaceblobstore/azureml/bert-classifier-test_1580753255_d05099c4/azureml-setup/context_manager_injector.py", line 243, in <module>
    execute_with_context(cm_objects, options.invocation)
  File "/mnt/batch/tasks/shared/LS_root/jobs/<HIDDEN>/azureml/bert-classifier-test_1580753255_d05099c4/mounts/workspaceblobstore/azureml/bert-classifier-test_1580753255_d05099c4/azureml-setup/context_manager_injector.py", line 82, in execute_with_context
    stack.enter_context(wrapper)
  File "/mnt/batch/tasks/shared/LS_root/jobs/<HIDDEN>/azureml/bert-classifier-test_1580753255_d05099c4/mounts/workspaceblobstore/azureml/bert-classifier-test_1580753255_d05099c4/azureml-setup/_vendor_contextlib2.py", line 356, in enter_context
    result = _cm_type.__enter__(cm)
  File "/mnt/batch/tasks/shared/LS_root/jobs/<HIDDEN>/azureml/bert-classifier-test_1580753255_d05099c4/mounts/workspaceblobstore/azureml/bert-classifier-test_1580753255_d05099c4/azureml-setup/context_manager_injector.py", line 44, in __enter__
    self.context_manager.__enter__()
  File "/mnt/batch/tasks/shared/LS_root/jobs/<HIDDEN>/azureml/bert-classifier-test_1580753255_d05099c4/mounts/workspaceblobstore/azureml/bert-classifier-test_1580753255_d05099c4/azureml-setup/context_managers.py", line 226, in __enter__
    self.datasets.__enter__()
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/context_managers.py", line 118, in __enter__
    context_manager = dataset.mount(mount_point=target_path)
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/_loggerfactory.py", line 78, in wrapper
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/file_dataset.py", line 191, in mount
    base_path = _find_path_prefix(self._dataflow)
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/file_dataset.py", line 281, in _find_path_prefix
    return None if path is None else _get_prefix(path, dataflow)
  File "/azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/python3.6/site-packages/azureml/data/file_dataset.py", line 294, in _get_prefix
    paths = [r['PortablePath'] for r in dataflow.take(1)._to_pyrecords()]
AttributeError: 'Dataflow' object has no attribute '_to_pyrecords'

2020/02/03 18:08:48 mpirun version string: {
mpirun (Open MPI) 3.1.2

Report bugs to http://www.open-mpi.org/community/help/
}

Error occurred: Dataset initialization failed: 'Dataflow' object has no attribute '_to_pyrecords'
```

I also run into an error with estimator3 (train_horovod.py), but the error message is different:

```
bash: /azureml-envs/azureml_b705a44b160b7c072bc83870a99f2817/lib/libtinfo.so.5: no version information available (required by bash)
--------------------------------------------------------------------------
Open RTE detected a bad parameter in the hostfile:
    /mnt/batch/tasks/shared/LS_root/jobs/<HIDDEN>/azureml/bert-classifier-test_1580753403_181d7300/wd/hostfile
The max_slots parameter is less than the slots parameter:
    slots=2
    max_slots=1
--------------------------------------------------------------------------
[6d510d47c13445b1917289737a6d79ae000000:00114] [[15828,0],0] ORTE_ERROR_LOG: Bad parameter in file util/hostfile/hostfile.c at line 407
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[15828,0],0] FORCE-TERMINATE AT (null):1 - error base/ras_base_allocate.c(302)

This is something that should be reported to the developers.
--------------------------------------------------------------------------

Error occurred: AzureMLCompute job failed.
JobFailed: Submitted script failed with a non-zero exit code; see the driver log file for details.
```

I am running the Jupyter notebook inside Azure Notebook VM in the Azure ML Service. The GPU cluster type is different from the instructions, since my subscription does not allow using the NC12s_v3 GPUs. I am using NC6 GPUs (which are part of NC Promotion offer), could this cause the script to crash?

**Comment by ACFwebmaster** [comment]
Hi lehmus

I was hitting the same wall and seemed to git rid of it by updating the pip dependcies in the TensorFlow settings so that "azureml-dataprep" referenced the latest version (1.1.38)

estimator2 = TensorFlow(source_directory='.',
                        entry_script='train_logging.py',
                        compute_target=compute_target, 
                        script_params = script_params,
                        framework_version='2.0',
                        use_gpu=True,
                        pip_packages=['transformers==2.0.0', 'azureml-dataprep[fuse,pandas]==**1.1.38**'])

**Comment by lehmus** [comment]
The fix provided by @ACFwebmaster worked for me as well. Thank you very much!
